### ISSUE TITLE
Auto-publishing MAJOR / MINOR / PATCH version

### ISSUE THREAD

**Issue by juanca** [mavenlink/orbs#5]
This can be achieved with CircleCI flows. Something like:

```
- publish_job:
    filter:
      branch: master
    steps:
      - circleci orb publish src/git/orb.yml mavenlink/git@X.Y.Z
```

1. Should only publish if the appropriate workflow passes
2. Merge commit dictates the type of bump: major / minor / patch
